<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="New" name="Labels Validation" tests="1" failures="1" timestamp="26 May 2021 18:26:03 GMT" time="17.967" errors="0">
  <testcase name="Labelsvalidation" time="0.181" classname="E2E.ValidateLabels">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at E2E.ValidateLabels.Labelsvalidation(ValidateLabels.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Labelsvalidation -->
</testsuite> <!-- Labels Validation -->
